Exercise 1

In [1]:
import numpy as np
import random

from dask.array import average
from streamlit import columns

arr = np.array(random.sample(range(1, 100), 25)).reshape(5, 5)
arr

array([[40, 88, 33, 71, 61],
       [76,  1, 62, 79, 41],
       [64, 32,  8, 94, 49],
       [42, 31, 25, 24, 59],
       [44, 28, 18, 26, 13]])

In [2]:
arr.sort(axis=1)
arr

array([[33, 40, 61, 71, 88],
       [ 1, 41, 62, 76, 79],
       [ 8, 32, 49, 64, 94],
       [24, 25, 31, 42, 59],
       [13, 18, 26, 28, 44]])

In [3]:
meanVal = arr.mean()
# arr.sum()/arr.size
meanVal

44.36

In [4]:
arr[arr>meanVal] = 0
arr

array([[33, 40,  0,  0,  0],
       [ 1, 41,  0,  0,  0],
       [ 8, 32,  0,  0,  0],
       [24, 25, 31, 42,  0],
       [13, 18, 26, 28, 44]])

In [5]:
arr @ arr.T

array([[2689, 1673, 1544, 1792, 1149],
       [1673, 1682, 1320, 1049,  751],
       [1544, 1320, 1088,  992,  680],
       [1792, 1049,  992, 3926, 2744],
       [1149,  751,  680, 2744, 3889]])

Exercise 2

In [16]:
import pandas as pd

file = pd.read_csv("data.csv")
df = pd.DataFrame(file)
df

Category  Quantity  Revenue
0        A        10      100
1        A         5       50
2        B         8      120
3        B        12      180
4        C         3       30
5        C         7       70
6        C        10      100
7        D        15      225

In [52]:
group_by_category = df.groupby('Category').sum()
group_by_category

Quantity  Revenue
Category                   
A               15      150
B               20      300
C               20      200
D               15      225

In [76]:
averagePrice = group_by_category['Revenue'].div(group_by_category['Quantity'])
averagePrice

Category
A    10.0
B    15.0
C    10.0
D    15.0
dtype: float64

In [67]:
maxAv = averagePrice[averagePrice.index].max()
for cat in averagePrice.index:
    if averagePrice[cat]==maxAv:
        print(cat, averagePrice[cat])

B 15.0
D 15.0


Exercise 3

In [74]:
arr = np.array(random.randint())
arr

TypeError: Random.randint() missing 2 required positional arguments: 'a' and 'b'

Exercise 4

In [2]:
import pandas as pd

In [33]:
df = pd.read_csv("sales_data.csv", parse_dates = ['Date'])
df

Date      Product  Quantity  Revenue
0  2022-01-01        Shoes      10.0     1000
1  2022-01-01         Bags       5.0      500
2  2022-01-01  Electronics       NaN      300
3  2022-02-01        Shoes       8.0      800
4  2022-02-01         Bags       3.0      300
..        ...          ...       ...      ...
67 2023-09-06         Bags       8.0      800
68 2023-09-07  Electronics       3.0      450
69 2023-09-08        Shoes      12.0     1200
70 2023-09-09         Bags       NaN      600
71 2023-05-01  Electronics       2.0      300

[72 rows x 4 columns]

In [34]:
df['Year'] = df['Date'].dt.year
df

Date      Product  Quantity  Revenue  Year
0  2022-01-01        Shoes      10.0     1000  2022
1  2022-01-01         Bags       5.0      500  2022
2  2022-01-01  Electronics       NaN      300  2022
3  2022-02-01        Shoes       8.0      800  2022
4  2022-02-01         Bags       3.0      300  2022
..        ...          ...       ...      ...   ...
67 2023-09-06         Bags       8.0      800  2023
68 2023-09-07  Electronics       3.0      450  2023
69 2023-09-08        Shoes      12.0     1200  2023
70 2023-09-09         Bags       NaN      600  2023
71 2023-05-01  Electronics       2.0      300  2023

[72 rows x 5 columns]

In [38]:
miss = df.isna().sum()
miss

Date         0
Product      0
Quantity    10
Revenue      0
Year         0
dtype: int64

In [ ]:
df['Quantity'].fillna(df['Quantity'].median())
df.groupby('Category').sum()