In [23]:
import numpy as np
import random

arr = np.arange(1,10).reshape(3,3)
# arr = np.array(random.sample(arr,3))
# arr.shape
# arr.ndim
# type(arr)
arr
arr.dtype

dtype('int64')

In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
arr1 = np.arange(10, 30 ,5).reshape(4,1)
arr1

array([[10],
       [15],
       [20],
       [25]])

In [51]:
arr = np.array([[1,2,3],
                [5,6,7]])

arr1 = np.array([[3,7,2]])
arr * arr1

array([[ 3, 14,  6],
       [15, 42, 14]])

In [59]:
a = np.array([[3.,7.,3.,4.],
              [1., 4., 2., 2.],
              [7., 2., 4., 9.,]])
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [65]:
a.resize((2,10), refcheck=False)

array([[3., 7., 3., 4., 1., 4., 2., 2., 7., 2.],
       [4., 9., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
import pandas as pd

s = pd.Series([1,3,5, np.nan, 6, 8])
s

0     1
1     3
2     5
3   NaN
4     6
5     8
dtype: float64

In [69]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [71]:
df = pd.DataFrame(np.random.randint(6,4), index=dates, columns = list('ABCD'))
df

ValueError: low >= high